//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LainausjarjestelmaMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LainausjarjestelmaEntities : DbContext
    {
        public LainausjarjestelmaEntities()
            : base("name=LainausjarjestelmaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Lainaajat> Lainaajat { get; set; }
        public virtual DbSet<Lainaukset> Lainaukset { get; set; }
        public virtual DbSet<Logins> Logins { get; set; }
        public virtual DbSet<Tuotteet> Tuotteet { get; set; }
        public virtual DbSet<Varastot> Varastot { get; set; }
    }
}
